spring.config.import=optional:file:./src/main/resources/application-secret.properties

spring.application.name=cput-campus-connect

server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://localhost:3306/campus_events_db
spring.datasource.username=root
spring.datasource.password=password

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Secrets
security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=36000000