JWT_SECRET=d1d9445607a9a9cc63ae2fc2497f9c8215f69e0656d3c6b1fd779cfe6676255e
DATABASE_URL=jdbc:mysql://localhost:3306/campus_connect_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
DB_USERNAME=root
DB_PASSWORD=
PORT=8080